
services:
  app:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
    command: ["python", "main.py"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"
